version: '3.4'

services:
  stamacasa.api:
    image: ${DOCKER_REGISTRY-}stamacasaapi
    build:
      context: .
      dockerfile: StamAcasa.Api/Dockerfile
    ports: 
      - 5001:80

  rabbitmq:
    image: local_rabbit
    restart: always
    container_name: rabbitmq
    build: 
      context: rabbitconfig/
      dockerfile: Dockerfile
    ports:
       # The standard AMQP protocol port
      - 5672:5672
        # HTTP management UI
      - 15672:15672

  identityserver:
    image: identityserver_img
    container_name: identityserver
    build:
        context: .
        dockerfile: StamAcasa.IdentityServer/Dockerfile
    ports: 
      - 5000:5000