version: '3.4'

services:
  stamacasa.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
